### ISSUE TITLE
Request already dispatched and commited somewhere else, not forwarding

### ISSUE THREAD

**Issue by pbaris** [caelum/vraptor4#981] opened 2015-05-18 10:45 UTC
When forwarding from a controller to an other i get `Request already dispatched and commited somewhere else, not forwarding` from method `br.com.caelum.vraptor.observer.ForwardToDefaultView#forward` and instead of rendering my jsp page a get a white page.

This happens because when `result.forward` is called it ends in `br.com.caelum.vraptor.core.DefaultResult#use` where result marks response as commited `responseCommitted = true;`

**Comment by Turini** [comment] 2015-07-10 23:42
Hi, @pbaris! I'm trying to reproduce this issue, but looks like it's ok now.
My test with the current master was:
```java
@Controller
public class OtherController {
	
	@Inject private Result result;
	
	public void index() {
		result.forwardTo(IndexController.class).index();
	}
}

@Controller
public class IndexController {

	@Inject private Result result;

	public void index() {
		result.include("variable", "VRaptor!");
	}
}
```
Am I missing something? Let me know if it's working for you too, so we can close the issue.
thank you so much for reporting this

**Comment by pbaris** [comment] 2015-07-13 07:20
Hi, @Turini! Testing it with version `4.2.0-RC2` i cannot reproduce it either. But if i use `forwardTo` with a string instead of a class i get the exception

```
java.lang.IllegalArgumentException: method public void vtests.PageController.index() cannot be invoked on clazz vtests.IndexController$Proxy$_$$_WeldClientProxy
	at net.vidageek.mirror.invoke.MethodHandlerByMethod.<init>(MethodHandlerByMethod.java:38) [mirror-1.6.1.jar:]
	at net.vidageek.mirror.invoke.DefaultInvocationHandler.method(DefaultInvocationHandler.java:65) [mirror-1.6.1.jar:]
	at br.com.caelum.vraptor.core.DefaultReflectionProvider.invoke(DefaultReflectionProvider.java:42) [vraptor-4.2.0-RC2.jar:]
	at br.com.caelum.vraptor.core.DefaultReflectionProvider$Proxy$_$$_WeldClientProxy.invoke(Unknown Source) [vraptor-4.2.0-RC2.jar:]
```

**Comment by Turini** [comment] 2015-07-19 03:46
Hi @pbaris, sorry about my delay answering. This other bug was already fixed here: https://github.com/caelum/vraptor4/issues/977. I intent to release a new version including this fix this week.

**Comment by Turini** [comment] 2015-07-19 03:48
I'm closing here, since we can't reproduce this bug. Please, reopen if it happens again :)

**Closed by Turini** 2015-07-19 03:48 UTC
Labels: bug
